name: Cron - goals

on:
  # "Scheduled workflows run on the latest commit on the default or base branch."
  # — https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows#schedule
  schedule:
    - cron: "5 * * * *"
jobs:
  cron-goals:
    runs-on: ubuntu-latest
    steps:
      - name: cURL request
        run: |
          curl http://localhost:3000/api/github/torvalds/linux \
            -X GET \
            --fail
